# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tips = QtWidgets.QLabel(self.centralwidget)
        self.tips.setObjectName("tips")
        self.verticalLayout_2.addWidget(self.tips)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.MainLayout = QtWidgets.QHBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.img_MainLayout = QtWidgets.QHBoxLayout()
        self.img_MainLayout.setObjectName("img_MainLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.text_Origin = QtWidgets.QLabel(self.centralwidget)
        self.text_Origin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.text_Origin.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Origin.setObjectName("text_Origin")
        self.gridLayout.addWidget(self.text_Origin, 0, 0, 1, 1)
        self.text_Prev = QtWidgets.QLabel(self.centralwidget)
        self.text_Prev.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Prev.setObjectName("text_Prev")
        self.gridLayout.addWidget(self.text_Prev, 0, 1, 1, 1)
        self.menu_MainLayout = QtWidgets.QGridLayout()
        self.menu_MainLayout.setObjectName("menu_MainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_open = QtWidgets.QPushButton(self.centralwidget)
        self.button_open.setObjectName("button_open")
        self.horizontalLayout.addWidget(self.button_open)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.menu_MainLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menu_MainLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setObjectName("button_1")
        self.verticalLayout.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setObjectName("button_2")
        self.verticalLayout.addWidget(self.button_2)
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setObjectName("button_3")
        self.verticalLayout.addWidget(self.button_3)
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setObjectName("button_4")
        self.verticalLayout.addWidget(self.button_4)
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setObjectName("button_5")
        self.verticalLayout.addWidget(self.button_5)
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setObjectName("button_6")
        self.verticalLayout.addWidget(self.button_6)
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setObjectName("button_7")
        self.verticalLayout.addWidget(self.button_7)
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setObjectName("button_8")
        self.verticalLayout.addWidget(self.button_8)
        self.menu_MainLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.menu_MainLayout.setRowStretch(0, 2)
        self.gridLayout.addLayout(self.menu_MainLayout, 1, 2, 1, 1)
        self.slider_origin = QtWidgets.QSlider(self.centralwidget)
        self.slider_origin.setOrientation(QtCore.Qt.Horizontal)
        self.slider_origin.setObjectName("slider_origin")
        self.gridLayout.addWidget(self.slider_origin, 2, 0, 1, 1)
        self.slider_prev = QtWidgets.QSlider(self.centralwidget)
        self.slider_prev.setOrientation(QtCore.Qt.Horizontal)
        self.slider_prev.setObjectName("slider_prev")
        self.gridLayout.addWidget(self.slider_prev, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 294))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_origin = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_origin.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.img_origin.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.img_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.img_origin.setObjectName("img_origin")
        self.horizontalLayout_2.addWidget(self.img_origin)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 350, 294))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_prev = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.img_prev.setAlignment(QtCore.Qt.AlignCenter)
        self.img_prev.setObjectName("img_prev")
        self.verticalLayout_3.addWidget(self.img_prev)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 1, 1, 1, 1)
        self.img_MainLayout.addLayout(self.gridLayout)
        self.MainLayout.addLayout(self.img_MainLayout)
        self.verticalLayout_2.addLayout(self.MainLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 23))
        self.menubar.setObjectName("menubar")
        self.menuwenjian = QtWidgets.QMenu(self.menubar)
        self.menuwenjian.setObjectName("menuwenjian")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuwenjian.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像处理-wjsaya.top"))
        self.tips.setText(_translate("MainWindow", "Tips"))
        self.text_Origin.setText(_translate("MainWindow", "原图"))
        self.text_Prev.setText(_translate("MainWindow", "预览"))
        self.button_open.setText(_translate("MainWindow", "打开"))
        self.button_save.setText(_translate("MainWindow", "保存"))
        self.button_1.setText(_translate("MainWindow", "彩色->灰度"))
        self.button_2.setText(_translate("MainWindow", "灰度->二值"))
        self.button_3.setText(_translate("MainWindow", "几何变换"))
        self.button_4.setText(_translate("MainWindow", "去噪"))
        self.button_5.setText(_translate("MainWindow", "PushButton"))
        self.button_6.setText(_translate("MainWindow", "边缘提取(一阶差分)"))
        self.button_7.setText(_translate("MainWindow", "加噪"))
        self.button_8.setText(_translate("MainWindow", "退出"))
        self.img_origin.setText(_translate("MainWindow", "原图"))
        self.img_prev.setText(_translate("MainWindow", "预览"))
        self.menuwenjian.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))

